"""interfaces untuk request Informasi Account."""

from typing import Protocol, runtime_checkable

from src.domains.digipos.dto import ReqUsername, ReqUsnOtp, ReqUsnPassword


@runtime_checkable
class IDigiposAccountService(Protocol):
    async def login(self, params: ReqUsnPassword): ...

    async def verify_otp(self, params: ReqUsnOtp): ...

    async def balance(self, params: ReqUsername): ...

    async def profile(self, params: ReqUsername): ...

    async def reward(self, params: ReqUsername): ...

    async def ticketva(self, params: ReqUsername): ...

    async def banner(self, params: ReqUsername): ...

    async def logout(self, params: ReqUsername): ...
