[application]
# ini nanti akan menjadi debugging untuk hal lain
debug = true



[digipos]
# debug flag spesifik
debug = true
# base url
base_url = "http://10.0.0.3:10003/"

# credentials
username = "WIR6289504"
password = "yourpassword"
pin = "yourpin"
