[digipos]
# base url
base_url = "http://10.0.0.3:10003/"

# credentials
username = "WIR6289504"
password = "yourpassword"
pin = "yourpin"

[digipos.response]
type = "text"

[digipos.endpoints]
login = "add_account"
verify_otp = "add_account_otp"
balance = "balance"
profile = "profile"
list_va = "list_va"
logout = "logout"
reward = "reward_summary"
banner= "banner"
sim_status ="sim_status"
